In [29]:
from clipper_admin import ClipperConnection, DockerContainerManager

In [30]:
clipper_conn = ClipperConnection(DockerContainerManager())

In [99]:
clipper_conn.connect()

24-01-23:16:48:27 INFO     [clipper_admin.py:172] [default-cluster] Successfully connected to Clipper cluster at localhost:1337


In [5]:
clipper_conn.get_all_models()

[]

In [6]:
clipper_conn.get_all_apps()

[]

In [2]:
import json
import base64
import requests
from datetime import datetime
import time
from PIL import Image
from IPython.display import display
import numpy
import re

In [4]:
app_name = 'pytorch-irevnet-app'
headers = {'Content-type': 'application/json'}
url = "http://172.24.128.1:1337/{app_name}/predict".format(
    app_name=app_name)

start = datetime.now()
req_json = json.dumps({ "input": base64.b64encode(open('/root/datatest/cifar10/test/1.jpg', "rb").read()).decode() })
r = requests.post(url, headers=headers, data=req_json)
end = datetime.now()

latency = (end - start).total_seconds() * 1000.0
print("%f ms" % (latency))
print(r.json()["output"])

53.023000 ms
[b'\x80\x03ctorch._utils\n_rebuild_tensor_v2\nq\x00(ctorch.storage\n_load_from_bytes\nq\x01B#\x01\x00\x00\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02(X\x07\x00\x00\x00storageq\x00ctorch\nFloatStorage\nq\x01X\x0e\x00\x00\x0094693339565136q\x02X\x03\x00\x00\x00cpuq\x03K\nNtq\x04Q.\x80\x02]q\x00X\x0e\x00\x00\x0094693339565136q\x01a.\n\x00\x00\x00\x00\x00\x00\x000,\r\xbeh\xd1\xcc=\x80\xbaj=\xb0\x04f>\xf0\xec\xbc= )\xed;h9\r\xbd`{i=8\xfbN\xbe\xe0+(\xbeq\x02\x85q\x03Rq\x04K\x00K\x01K\n\x86q\x05K\nK\x01\x86q\x06\x89ccollections\nOrderedDict\nq\x07)Rq\x08tq\tRq\n.', b'\x80\x03ctorch._utils\n_rebuild_tensor_v2\nq\x00(ctorch.storage\n_load_from_bytes\nq\x01B\xfc\x00\x02\x00\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x8

In [62]:
app_name = 'pytorch-irevnet-app'
headers = {'Content-type': 'application/json'}
url = "http://172.24.128.2:1337/{app_name}/predict".format(
    app_name=app_name)

start = datetime.now()
req_json = json.dumps({ "input": base64.b64encode(open('/root/datatest/cifar10/test/1.jpg', "rb").read()).decode() })
r = requests.post(url, headers=headers, data=req_json)
end = datetime.now()

latency = (end - start).total_seconds() * 1000.0
print("%f ms" % (latency))
print(r.json()["output"])

51.722000 ms
[b'\x80\x03ctorch._utils\n_rebuild_tensor_v2\nq\x00(ctorch.storage\n_load_from_bytes\nq\x01B#\x01\x00\x00\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02(X\x07\x00\x00\x00storageq\x00ctorch\nFloatStorage\nq\x01X\x0e\x00\x00\x0094493382065088q\x02X\x03\x00\x00\x00cpuq\x03K\nNtq\x04Q.\x80\x02]q\x00X\x0e\x00\x00\x0094493382065088q\x01a.\n\x00\x00\x00\x00\x00\x00\x00\x00\xcd$\xbe\x98\xe1\xe5=\x003\x89;\x18\xaf;>\xf4\xb6\xb2=\xc4\x9e\x12=\x1e#\xa6\xbd\x88N\xbd=\x9e\xf6\x0e\xbeX\x06\t\xbeq\x02\x85q\x03Rq\x04K\x00K\x01K\n\x86q\x05K\nK\x01\x86q\x06\x89ccollections\nOrderedDict\nq\x07)Rq\x08tq\tRq\n.', b'\x80\x03ctorch._utils\n_rebuild_tensor_v2\nq\x00(ctorch.storage\n_load_from_bytes\nq\x01B\xfc\x00\x02\x00\x80\x02\x8a\nl\xfc\x9cF\xf9 

In [10]:
import random
import numpy as np

x1=np.random.poisson(lam=1000.0,size=1000)
# print(1e6 / 1000)
# print(x1)
x2 = x1 / np.sum(x1)
print(np.sum(x2))
# print(1e2)

1000.0


In [50]:
latency = (end - start).total_seconds() * 1000.0
# print("'%s', %f ms" % (r.text, latency))
print("%f ms" % (latency))
print(r.json()["output"])

74.393000 ms
[b'\x80\x03ctorch._utils\n_rebuild_tensor_v2\nq\x00(ctorch.storage\n_load_from_bytes\nq\x01B#\x01\x00\x00\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02(X\x07\x00\x00\x00storageq\x00ctorch\nFloatStorage\nq\x01X\x0e\x00\x00\x0094827393911232q\x02X\x03\x00\x00\x00cpuq\x03K\nNtq\x04Q.\x80\x02]q\x00X\x0e\x00\x00\x0094827393911232q\x01a.\n\x00\x00\x00\x00\x00\x00\x00X\xa5\x1c\xbe\xd8Z\x86=\xe0A7\xbd\xd4rK>\xc4\xc9\x08>X_a<\x80\x88x<\x00\x1e\xe5\xbc\xd8\xba\xc1\xbd\x80\xb2\xda\xbdq\x02\x85q\x03Rq\x04K\x00K\x01K\n\x86q\x05K\nK\x01\x86q\x06\x89ccollections\nOrderedDict\nq\x07)Rq\x08tq\tRq\n.', b'\x80\x03ctorch._utils\n_rebuild_tensor_v2\nq\x00(ctorch.storage\n_load_from_bytes\nq\x01B\xfc\x00\x02\x00\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\

In [33]:
import torch
import numpy as np

x = torch.zeros([2,5],dtype=torch.float)
y = torch.zeros([2,5],dtype=torch.float)
# print(x)
# print(np.count_nonzero(x))
for i,data in enumerate(x):
    print(data)

tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])


In [7]:
import torch
if torch.cuda.is_available():
    x = torch.rand(16, 64, 64)
    # device = torch.device("cuda")          # a CUDA 设备对象
    # x = x.to(device)  # 或者直接使用``.to("cuda")``将张量移动到cuda中
    # z = x + y
    # print(z)
    # print(z.to("cpu", torch.double))  # ``.to`` 也会对变量的类型做更改
    x = x.cuda()
    print(x.device)

cuda:0


In [14]:
from torchvision.models.resnet import resnet50
model = resnet50(pretrained=True)

# print(model.device)   
model = model.cuda()
print(model.is_cuda())  


AttributeError: 'ResNet' object has no attribute 'is_cuda'

In [22]:
import torch
import numpy
import models.iRevNet

path = "/root/i-NeDD/model/checkpoint/distill/models/iRevNet18/S_iRevNet16x64_T_iRevNet18_cifar10/iRevNet16x64_best-para.pth"
print("=> loading distill model '{}'".format(path))
model = models.iRevNet.iRevNet16x64()
model.load_state_dict(torch.load(path))
print("=> loaded distill model '{}'".format(path))

model = model.cuda()

x = torch.rand(16, 64, 64)
x = x.unsqueeze(0).cuda()
y,_ = model(x)
print(y[0].shape)
print(type(y[0]))
print(y.cpu().data[0].numpy())
# out = y.data[0]

=> loading distill model '/root/i-NeDD/model/checkpoint/distill/models/iRevNet18/S_iRevNet16x64_T_iRevNet18_cifar10/iRevNet16x64_best-para.pth'

 == Building iRevNet 37 == 

| Injective iRevNet |

=> loaded distill model '/root/i-NeDD/model/checkpoint/distill/models/iRevNet18/S_iRevNet16x64_T_iRevNet18_cifar10/iRevNet16x64_best-para.pth'
torch.Size([10])
<class 'torch.Tensor'>
[-0.14632702  0.05093043  0.26912123  0.76473606  0.08247918  0.14437252
 -0.05974305 -0.2766143  -0.52676636 -0.30300987]


In [ ]:
import torch
import json
import numpy as np
import time

str_output = r.json()["output"]
# print(str_output)
json_output = eval(str_output)
start = time.time()
np_out = np.fromstring(json_output[0], sep=' ')
# np_outbij = np.fromstring(json_output[1], sep=' ').reshape((512, 8, 8))
end = time.time()
print("{} ms".format(float(end-start)*1000.0))
print(type(np_out))
print(np_out.shape)
# print(type(np_outbij))
# print(np_outbij.shape)

In [16]:
import torch
import numpy as np
t = torch.rand([10])
print(t)
y = t.numpy()
print(y)
print(y.argmax())

tensor([0.8484, 0.4876, 0.5174, 0.5314, 0.7530, 0.4622, 0.9318, 0.2958, 0.9040,
        0.1653])
[0.8484308  0.48759437 0.51744765 0.53144646 0.7530271  0.4622478
 0.9317708  0.29575247 0.9039699  0.16531748]
6


In [21]:
import json
import pickle

str_output = r.json()["output"]
json_output = eval(str_output)
# print(json_output[0])
# dict_data = json.loads(json_output[0])
# print(dict_data['output'])
start = time.time()
data1 = pickle.loads(json_output[0])
data2 = pickle.loads(json_output[1])
end = time.time()
print("{} ms".format(float(end-start)*1000.0))
# print(data1.numpy())
print(data1.cpu().numpy())

1.2063980102539062 ms


TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [93]:
import torch
import json
import numpy as np

str_output = r.json()["output"]
json_output = eval(str_output)
np_outbij = np.fromstring(json_output[0]['out_bij'], sep=' ').reshape((512,8,8))
np_out = np.fromstring(json_output[0]['out'], sep=' ')
print(type(np_outbij))
print(np_outbij.shape)
print(type(np_out[0]))
print(np_out.shape)

TypeError: byte indices must be integers or slices, not str

In [10]:
import torch 
x = torch.tensor([[1,2],[1,2],[1,2]])
print(x.reshape(2,3))
print(x.shape)
in_dim = {
    "cifar10": (2,3),
}
x.reshape(in_dim["cifar10"])
x.reshape(list(in_dim["cifar10"]))



torch.Size([3, 2])


tensor([[1, 2, 1],
        [2, 1, 2]])

In [108]:
id_list = [1,2,3]
out_list = [234,34,67]
print(id_list+out_list)

id_str_list=[str(i) for i in id_list]
print(id_str_list)
str1 = ' '.join(id_str_list)
print(str1)

i=2
print(id_list[:-1])

[1, 2, 3, 234, 34, 67]
['1', '2', '3']
1 2 3
[1, 2]


# Clean-up

In [26]:
clipper_conn.stop_all()

19-06-09:01:19:45 INFO     [clipper_admin.py:1424] [default-cluster] Stopped all Clipper cluster and all model containers


In [107]:
!docker rm -f $(docker ps -a -q) && docker image prune -f

020421ab352a
ce4874bf4700
1af329673c8a
8244f5ae8cb4
947019231e9b
1112af8baa7f
Deleted Images:
deleted: sha256:16c972c67594487b81904d8a990077d918c384eb05e3e69b3f9a496bf00bd0de
deleted: sha256:a27e6ce343bc455e9596100ba499821be2ecdd5c5d6bbe202f066db50699cd17

Total reclaimed space: 63.92MB
